### ISSUE TITLE
Finish the "user" CLI command

### ISSUE THREAD

**Issue by astoeckel** [astoeckel/tivua#11]
The `user` CLI command is partially implemented and needs to be tested/completed.

In particular
* Deleting users has never been tested. This is also required for the user manager.
* Deleting a user does not delete a user's posts. The documentation and the messages printed on screen need to be adapted.
* There should be a sub command for printing all users, i.e. `tivua user list`, akin to the output of just running `SELECT * FROM users;` in sqlite.

See also #24

**Comment by Thomas-Lu** [comment]
https://github.com/astoeckel/tivua/pull/49
